# Generated by Django 4.2.4 on 2024-08-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamattempt',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentexamattempt',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
