# Generated by Django 4.2.4 on 2024-08-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquizattempt',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
