# Generated by Django 4.2.4 on 2024-08-05 01:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Mocktest', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('challengeID', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyChallengeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenge_questions', to='DailyChallenge.dailychallenge')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mocktest.mockquestions')),
            ],
        ),
        migrations.CreateModel(
            name='DailyChallengeLeaderboard',
            fields=[
                ('leaderboardID', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('completion_time', models.DurationField()),
                ('daily_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='DailyChallenge.dailychallenge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenge_scores', to='User.student')),
            ],
            options={
                'unique_together': {('daily_challenge', 'student')},
            },
        ),
    ]
