# Generated by Django 4.2.4 on 2024-08-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyChallenge', '0002_dailychallengeleaderboard_totalquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychallengeleaderboard',
            name='completion_time',
            field=models.DateTimeField(),
        ),
    ]
