# Generated by Django 4.2.4 on 2024-08-05 08:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challengeID', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentChallengeAttempt',
            fields=[
                ('leaderboardID', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.IntegerField()),
                ('daily_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='Challenge.challenge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenge_scores', to='User.student')),
            ],
        ),
    ]
